### ISSUE TITLE
Keep the original URL on the first input

### ISSUE THREAD

**Issue by lucas-felinto** [lucas-felinto/url-shortner#1]
When we submit the form, the page refresh and we lost the original url.

**Comment by wejesuss** [comment]
Why don't you get the "full" property of the "shortUrls"?

**Comment by lucas-felinto** [comment]
That’s an ideia! But will be the same problem about the other issue. The application will start with an value already!

**Comment by wejesuss** [comment]
I just create a pull request a few minutes ago. Could you verify if this helps you? :)

**Comment by lucas-felinto** [comment]
Actually it doesn't work, Wemerson! We receive the full url but we didn't output the shorturl

**Comment by wejesuss** [comment]
I will verify it tomorrow :)
